/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'new' : IDL.Null,
  'resolved' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const VehicleType = IDL.Variant({
  'suv' : IDL.Null,
  'sedan' : IDL.Null,
});
export const CarRentalDetails = IDL.Record({
  'vehicleType' : VehicleType,
  'driverRequired' : IDL.Bool,
});
export const InquiryCategory = IDL.Variant({
  'tourInquiry' : IDL.Null,
  'carRental' : IDL.Null,
});
export const CustomerInquiry = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'rentalDetails' : IDL.Opt(CarRentalDetails),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'category' : InquiryCategory,
  'phoneNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TourPackage = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPackage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'deletePackage' : IDL.Func([IDL.Text], [], []),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(CustomerInquiry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPublicPackages' : IDL.Func([], [IDL.Vec(TourPackage)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitCarRental' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, VehicleType, IDL.Bool],
      [],
      [],
    ),
  'submitTourInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateInquiryStatus' : IDL.Func([IDL.Nat, Status], [], []),
  'updatePackage' : IDL.Func([IDL.Text, TourPackage], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'new' : IDL.Null,
    'resolved' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const VehicleType = IDL.Variant({ 'suv' : IDL.Null, 'sedan' : IDL.Null });
  const CarRentalDetails = IDL.Record({
    'vehicleType' : VehicleType,
    'driverRequired' : IDL.Bool,
  });
  const InquiryCategory = IDL.Variant({
    'tourInquiry' : IDL.Null,
    'carRental' : IDL.Null,
  });
  const CustomerInquiry = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'rentalDetails' : IDL.Opt(CarRentalDetails),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'category' : InquiryCategory,
    'phoneNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TourPackage = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPackage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'deletePackage' : IDL.Func([IDL.Text], [], []),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(CustomerInquiry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPublicPackages' : IDL.Func([], [IDL.Vec(TourPackage)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitCarRental' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, VehicleType, IDL.Bool],
        [],
        [],
      ),
    'submitTourInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateInquiryStatus' : IDL.Func([IDL.Nat, Status], [], []),
    'updatePackage' : IDL.Func([IDL.Text, TourPackage], [], []),
  });
};

export const init = ({ IDL }) => { return []; };