/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FlightBookingDetails {
    cabinClass: string;
    tripType: string;
    departureDate: string;
    passengerCount: bigint;
    destinationCity: string;
    returnDate?: string;
    originCity: string;
}
export interface CustomerInquiry {
    id: bigint;
    status: Status;
    rentalDetails?: CarRentalDetails;
    name: string;
    railwayBookingDetails?: RailwayBookingDetails;
    flightBookingDetails?: FlightBookingDetails;
    email: string;
    message: string;
    customPackageDetails?: CustomPackageDetails;
    category: InquiryCategory;
    phoneNumber: string;
}
export interface CustomPackageDetails {
    durationDays: bigint;
    destination: string;
    destinationType: string;
    numberOfTravelers: bigint;
    preferredDates?: string;
}
export interface RailwayBookingDetails {
    passengerCount: bigint;
    travelDate: string;
    railClass: string;
    originStation: string;
    destinationStation: string;
}
export interface TourPackage {
    id: string;
    title: string;
    duration: bigint;
    description: string;
    price: bigint;
}
export interface CarRentalDetails {
    estimatedDistance?: bigint;
    vehicleType: VehicleType;
    estimatedFare?: bigint;
    driverRequired: boolean;
}
export interface UserProfile {
    name: string;
}
export enum InquiryCategory {
    railwayBooking = "railwayBooking",
    flightBooking = "flightBooking",
    tourInquiry = "tourInquiry",
    customPackage = "customPackage",
    carRental = "carRental"
}
export enum Status {
    new_ = "new",
    resolved = "resolved",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VehicleType {
    suv = "suv",
    sedan = "sedan"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPackage(id: string, title: string, description: string, price: bigint, duration: bigint): Promise<void>;
    deletePackage(id: string): Promise<void>;
    getAllInquiries(): Promise<Array<CustomerInquiry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPublicPackages(): Promise<Array<TourPackage>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitCarRental(name: string, phoneNumber: string, email: string, vehicleType: VehicleType, driverRequired: boolean, estimatedDistance: bigint | null, estimatedFare: bigint | null): Promise<void>;
    submitCustomPackage(name: string, phoneNumber: string, email: string, destinationType: string, destination: string, numberOfTravelers: bigint, durationDays: bigint, preferredDates: string | null): Promise<void>;
    submitFlightBooking(name: string, phoneNumber: string, email: string, originCity: string, destinationCity: string, departureDate: string, returnDate: string | null, tripType: string, passengerCount: bigint, cabinClass: string): Promise<void>;
    submitRailwayBooking(name: string, phoneNumber: string, email: string, originStation: string, destinationStation: string, travelDate: string, passengerCount: bigint, railClass: string): Promise<void>;
    submitTourInquiry(name: string, phoneNumber: string, email: string, message: string): Promise<void>;
    updateInquiryStatus(inquiryId: bigint, newStatus: Status): Promise<void>;
    updatePackage(id: string, newPackage: TourPackage): Promise<void>;
}
import type { CarRentalDetails as _CarRentalDetails, CustomPackageDetails as _CustomPackageDetails, CustomerInquiry as _CustomerInquiry, FlightBookingDetails as _FlightBookingDetails, InquiryCategory as _InquiryCategory, RailwayBookingDetails as _RailwayBookingDetails, Status as _Status, UserProfile as _UserProfile, UserRole as _UserRole, VehicleType as _VehicleType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPackage(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPackage(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPackage(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async deletePackage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePackage(arg0);
            return result;
        }
    }
    async getAllInquiries(): Promise<Array<CustomerInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublicPackages(): Promise<Array<TourPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublicPackages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublicPackages();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitCarRental(arg0: string, arg1: string, arg2: string, arg3: VehicleType, arg4: boolean, arg5: bigint | null, arg6: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCarRental(arg0, arg1, arg2, to_candid_VehicleType_n27(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n29(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCarRental(arg0, arg1, arg2, to_candid_VehicleType_n27(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n29(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async submitCustomPackage(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: bigint, arg7: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitCustomPackage(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n30(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitCustomPackage(arg0, arg1, arg2, arg3, arg4, arg5, arg6, to_candid_opt_n30(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async submitFlightBooking(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string | null, arg7: string, arg8: bigint, arg9: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFlightBooking(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n30(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFlightBooking(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n30(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9);
            return result;
        }
    }
    async submitRailwayBooking(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint, arg7: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRailwayBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRailwayBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async submitTourInquiry(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitTourInquiry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitTourInquiry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateInquiryStatus(arg0: bigint, arg1: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInquiryStatus(arg0, to_candid_Status_n31(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInquiryStatus(arg0, to_candid_Status_n31(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePackage(arg0: string, arg1: TourPackage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePackage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePackage(arg0, arg1);
            return result;
        }
    }
}
function from_candid_CarRentalDetails_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CarRentalDetails): CarRentalDetails {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_CustomPackageDetails_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomPackageDetails): CustomPackageDetails {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_CustomerInquiry_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerInquiry): CustomerInquiry {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_FlightBookingDetails_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FlightBookingDetails): FlightBookingDetails {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_InquiryCategory_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InquiryCategory): InquiryCategory {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_VehicleType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VehicleType): VehicleType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RailwayBookingDetails]): RailwayBookingDetails | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FlightBookingDetails]): FlightBookingDetails | null {
    return value.length === 0 ? null : from_candid_FlightBookingDetails_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CustomPackageDetails]): CustomPackageDetails | null {
    return value.length === 0 ? null : from_candid_CustomPackageDetails_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CarRentalDetails]): CarRentalDetails | null {
    return value.length === 0 ? null : from_candid_CarRentalDetails_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    estimatedDistance: [] | [bigint];
    vehicleType: _VehicleType;
    estimatedFare: [] | [bigint];
    driverRequired: boolean;
}): {
    estimatedDistance?: bigint;
    vehicleType: VehicleType;
    estimatedFare?: bigint;
    driverRequired: boolean;
} {
    return {
        estimatedDistance: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.estimatedDistance)),
        vehicleType: from_candid_VehicleType_n12(_uploadFile, _downloadFile, value.vehicleType),
        estimatedFare: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.estimatedFare)),
        driverRequired: value.driverRequired
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cabinClass: string;
    tripType: string;
    departureDate: string;
    passengerCount: bigint;
    destinationCity: string;
    returnDate: [] | [string];
    originCity: string;
}): {
    cabinClass: string;
    tripType: string;
    departureDate: string;
    passengerCount: bigint;
    destinationCity: string;
    returnDate?: string;
    originCity: string;
} {
    return {
        cabinClass: value.cabinClass,
        tripType: value.tripType,
        departureDate: value.departureDate,
        passengerCount: value.passengerCount,
        destinationCity: value.destinationCity,
        returnDate: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.returnDate)),
        originCity: value.originCity
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    durationDays: bigint;
    destination: string;
    destinationType: string;
    numberOfTravelers: bigint;
    preferredDates: [] | [string];
}): {
    durationDays: bigint;
    destination: string;
    destinationType: string;
    numberOfTravelers: bigint;
    preferredDates?: string;
} {
    return {
        durationDays: value.durationDays,
        destination: value.destination,
        destinationType: value.destinationType,
        numberOfTravelers: value.numberOfTravelers,
        preferredDates: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.preferredDates))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    rentalDetails: [] | [_CarRentalDetails];
    name: string;
    railwayBookingDetails: [] | [_RailwayBookingDetails];
    flightBookingDetails: [] | [_FlightBookingDetails];
    email: string;
    message: string;
    customPackageDetails: [] | [_CustomPackageDetails];
    category: _InquiryCategory;
    phoneNumber: string;
}): {
    id: bigint;
    status: Status;
    rentalDetails?: CarRentalDetails;
    name: string;
    railwayBookingDetails?: RailwayBookingDetails;
    flightBookingDetails?: FlightBookingDetails;
    email: string;
    message: string;
    customPackageDetails?: CustomPackageDetails;
    category: InquiryCategory;
    phoneNumber: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n6(_uploadFile, _downloadFile, value.status),
        rentalDetails: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.rentalDetails)),
        name: value.name,
        railwayBookingDetails: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.railwayBookingDetails)),
        flightBookingDetails: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.flightBookingDetails)),
        email: value.email,
        message: value.message,
        customPackageDetails: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.customPackageDetails)),
        category: from_candid_InquiryCategory_n22(_uploadFile, _downloadFile, value.category),
        phoneNumber: value.phoneNumber
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    suv: null;
} | {
    sedan: null;
}): VehicleType {
    return "suv" in value ? VehicleType.suv : "sedan" in value ? VehicleType.sedan : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    railwayBooking: null;
} | {
    flightBooking: null;
} | {
    tourInquiry: null;
} | {
    customPackage: null;
} | {
    carRental: null;
}): InquiryCategory {
    return "railwayBooking" in value ? InquiryCategory.railwayBooking : "flightBooking" in value ? InquiryCategory.flightBooking : "tourInquiry" in value ? InquiryCategory.tourInquiry : "customPackage" in value ? InquiryCategory.customPackage : "carRental" in value ? InquiryCategory.carRental : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    resolved: null;
} | {
    inProgress: null;
}): Status {
    return "new" in value ? Status.new : "resolved" in value ? Status.resolved : "inProgress" in value ? Status.inProgress : value;
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomerInquiry>): Array<CustomerInquiry> {
    return value.map((x)=>from_candid_CustomerInquiry_n4(_uploadFile, _downloadFile, x));
}
function to_candid_Status_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_VehicleType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): _VehicleType {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VehicleType): {
    suv: null;
} | {
    sedan: null;
} {
    return value == VehicleType.suv ? {
        suv: null
    } : value == VehicleType.sedan ? {
        sedan: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    new: null;
} | {
    resolved: null;
} | {
    inProgress: null;
} {
    return value == Status.new ? {
        new_: null
    } : value == Status.resolved ? {
        resolved: null
    } : value == Status.inProgress ? {
        inProgress: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
