/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Status = IDL.Variant({
  'new' : IDL.Null,
  'resolved' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const VehicleType = IDL.Variant({
  'suv' : IDL.Null,
  'sedan' : IDL.Null,
});
export const CarRentalDetails = IDL.Record({
  'estimatedDistance' : IDL.Opt(IDL.Nat),
  'vehicleType' : VehicleType,
  'estimatedFare' : IDL.Opt(IDL.Nat),
  'driverRequired' : IDL.Bool,
});
export const RailwayBookingDetails = IDL.Record({
  'passengerCount' : IDL.Nat,
  'travelDate' : IDL.Text,
  'railClass' : IDL.Text,
  'originStation' : IDL.Text,
  'destinationStation' : IDL.Text,
});
export const FlightBookingDetails = IDL.Record({
  'cabinClass' : IDL.Text,
  'tripType' : IDL.Text,
  'departureDate' : IDL.Text,
  'passengerCount' : IDL.Nat,
  'destinationCity' : IDL.Text,
  'returnDate' : IDL.Opt(IDL.Text),
  'originCity' : IDL.Text,
});
export const HotelBookingDetails = IDL.Record({
  'destination' : IDL.Text,
  'starRating' : IDL.Opt(IDL.Nat),
  'hotelName' : IDL.Opt(IDL.Text),
  'pricePerNight' : IDL.Opt(IDL.Nat),
  'numberOfRooms' : IDL.Nat,
  'checkInDate' : IDL.Text,
  'roomTypePreference' : IDL.Text,
  'checkOutDate' : IDL.Text,
  'numberOfGuests' : IDL.Nat,
  'location' : IDL.Opt(IDL.Text),
});
export const CustomPackageDetails = IDL.Record({
  'durationDays' : IDL.Nat,
  'destination' : IDL.Text,
  'destinationType' : IDL.Text,
  'numberOfTravelers' : IDL.Nat,
  'preferredDates' : IDL.Opt(IDL.Text),
});
export const InquiryCategory = IDL.Variant({
  'railwayBooking' : IDL.Null,
  'hotelBooking' : IDL.Null,
  'flightBooking' : IDL.Null,
  'tourInquiry' : IDL.Null,
  'customPackage' : IDL.Null,
  'carRental' : IDL.Null,
});
export const CustomerInquiry = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'rentalDetails' : IDL.Opt(CarRentalDetails),
  'name' : IDL.Text,
  'railwayBookingDetails' : IDL.Opt(RailwayBookingDetails),
  'flightBookingDetails' : IDL.Opt(FlightBookingDetails),
  'email' : IDL.Text,
  'hotelBookingDetails' : IDL.Opt(HotelBookingDetails),
  'message' : IDL.Text,
  'customPackageDetails' : IDL.Opt(CustomPackageDetails),
  'category' : InquiryCategory,
  'phoneNumber' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TourPackage = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'description' : IDL.Text,
  'price' : IDL.Nat,
});
export const CarType = IDL.Variant({ 'suv' : IDL.Null, 'sedan' : IDL.Null });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPackage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'deletePackage' : IDL.Func([IDL.Text], [], []),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(CustomerInquiry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPublicPackages' : IDL.Func([], [IDL.Vec(TourPackage)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitCarRental' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, CarType, IDL.Bool, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'submitCustomPackage' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'submitFlightBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
  'submitHotelBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'submitRailwayBooking' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
      ],
      [],
      [],
    ),
  'submitTourInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateInquiryStatus' : IDL.Func([IDL.Nat, Status], [], []),
  'updatePackage' : IDL.Func([IDL.Text, TourPackage], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Status = IDL.Variant({
    'new' : IDL.Null,
    'resolved' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const VehicleType = IDL.Variant({ 'suv' : IDL.Null, 'sedan' : IDL.Null });
  const CarRentalDetails = IDL.Record({
    'estimatedDistance' : IDL.Opt(IDL.Nat),
    'vehicleType' : VehicleType,
    'estimatedFare' : IDL.Opt(IDL.Nat),
    'driverRequired' : IDL.Bool,
  });
  const RailwayBookingDetails = IDL.Record({
    'passengerCount' : IDL.Nat,
    'travelDate' : IDL.Text,
    'railClass' : IDL.Text,
    'originStation' : IDL.Text,
    'destinationStation' : IDL.Text,
  });
  const FlightBookingDetails = IDL.Record({
    'cabinClass' : IDL.Text,
    'tripType' : IDL.Text,
    'departureDate' : IDL.Text,
    'passengerCount' : IDL.Nat,
    'destinationCity' : IDL.Text,
    'returnDate' : IDL.Opt(IDL.Text),
    'originCity' : IDL.Text,
  });
  const HotelBookingDetails = IDL.Record({
    'destination' : IDL.Text,
    'starRating' : IDL.Opt(IDL.Nat),
    'hotelName' : IDL.Opt(IDL.Text),
    'pricePerNight' : IDL.Opt(IDL.Nat),
    'numberOfRooms' : IDL.Nat,
    'checkInDate' : IDL.Text,
    'roomTypePreference' : IDL.Text,
    'checkOutDate' : IDL.Text,
    'numberOfGuests' : IDL.Nat,
    'location' : IDL.Opt(IDL.Text),
  });
  const CustomPackageDetails = IDL.Record({
    'durationDays' : IDL.Nat,
    'destination' : IDL.Text,
    'destinationType' : IDL.Text,
    'numberOfTravelers' : IDL.Nat,
    'preferredDates' : IDL.Opt(IDL.Text),
  });
  const InquiryCategory = IDL.Variant({
    'railwayBooking' : IDL.Null,
    'hotelBooking' : IDL.Null,
    'flightBooking' : IDL.Null,
    'tourInquiry' : IDL.Null,
    'customPackage' : IDL.Null,
    'carRental' : IDL.Null,
  });
  const CustomerInquiry = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'rentalDetails' : IDL.Opt(CarRentalDetails),
    'name' : IDL.Text,
    'railwayBookingDetails' : IDL.Opt(RailwayBookingDetails),
    'flightBookingDetails' : IDL.Opt(FlightBookingDetails),
    'email' : IDL.Text,
    'hotelBookingDetails' : IDL.Opt(HotelBookingDetails),
    'message' : IDL.Text,
    'customPackageDetails' : IDL.Opt(CustomPackageDetails),
    'category' : InquiryCategory,
    'phoneNumber' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TourPackage = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'description' : IDL.Text,
    'price' : IDL.Nat,
  });
  const CarType = IDL.Variant({ 'suv' : IDL.Null, 'sedan' : IDL.Null });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPackage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'deletePackage' : IDL.Func([IDL.Text], [], []),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(CustomerInquiry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPublicPackages' : IDL.Func([], [IDL.Vec(TourPackage)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitCarRental' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, CarType, IDL.Bool, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'submitCustomPackage' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'submitFlightBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'submitHotelBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'submitRailwayBooking' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
        ],
        [],
        [],
      ),
    'submitTourInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateInquiryStatus' : IDL.Func([IDL.Nat, Status], [], []),
    'updatePackage' : IDL.Func([IDL.Text, TourPackage], [], []),
  });
};

export const init = ({ IDL }) => { return []; };