/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CarRentalDetails {
  'estimatedDistance' : [] | [bigint],
  'vehicleType' : VehicleType,
  'estimatedFare' : [] | [bigint],
  'driverRequired' : boolean,
}
export interface CustomPackageDetails {
  'durationDays' : bigint,
  'destination' : string,
  'destinationType' : string,
  'numberOfTravelers' : bigint,
  'preferredDates' : [] | [string],
}
export interface CustomerInquiry {
  'id' : bigint,
  'status' : Status,
  'rentalDetails' : [] | [CarRentalDetails],
  'name' : string,
  'railwayBookingDetails' : [] | [RailwayBookingDetails],
  'flightBookingDetails' : [] | [FlightBookingDetails],
  'email' : string,
  'message' : string,
  'customPackageDetails' : [] | [CustomPackageDetails],
  'category' : InquiryCategory,
  'phoneNumber' : string,
}
export interface FlightBookingDetails {
  'cabinClass' : string,
  'tripType' : string,
  'departureDate' : string,
  'passengerCount' : bigint,
  'destinationCity' : string,
  'returnDate' : [] | [string],
  'originCity' : string,
}
export type InquiryCategory = { 'railwayBooking' : null } |
  { 'flightBooking' : null } |
  { 'tourInquiry' : null } |
  { 'customPackage' : null } |
  { 'carRental' : null };
export interface RailwayBookingDetails {
  'passengerCount' : bigint,
  'travelDate' : string,
  'railClass' : string,
  'originStation' : string,
  'destinationStation' : string,
}
export type Status = { 'new' : null } |
  { 'resolved' : null } |
  { 'inProgress' : null };
export interface TourPackage {
  'id' : string,
  'title' : string,
  'duration' : bigint,
  'description' : string,
  'price' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VehicleType = { 'suv' : null } |
  { 'sedan' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPackage' : ActorMethod<
    [string, string, string, bigint, bigint],
    undefined
  >,
  'deletePackage' : ActorMethod<[string], undefined>,
  'getAllInquiries' : ActorMethod<[], Array<CustomerInquiry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPublicPackages' : ActorMethod<[], Array<TourPackage>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitCarRental' : ActorMethod<
    [
      string,
      string,
      string,
      VehicleType,
      boolean,
      [] | [bigint],
      [] | [bigint],
    ],
    undefined
  >,
  'submitCustomPackage' : ActorMethod<
    [string, string, string, string, string, bigint, bigint, [] | [string]],
    undefined
  >,
  'submitFlightBooking' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
      string,
      bigint,
      string,
    ],
    undefined
  >,
  'submitRailwayBooking' : ActorMethod<
    [string, string, string, string, string, string, bigint, string],
    undefined
  >,
  'submitTourInquiry' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updateInquiryStatus' : ActorMethod<[bigint, Status], undefined>,
  'updatePackage' : ActorMethod<[string, TourPackage], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];